# Nearest Neighbors

Nearst neighbor method is a nonparametric method used to density estimation that make few assumptions about the form of the distributions.



In [1]:
import jax.numpy as jnp 
import numpy as np 

from basic.neighbors import NearestNeighborsClassifier

In [4]:
# Generate some example training and test data
train_X = jnp.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
train_y = jnp.array([0, 1, 0, 1, 0])
test_X = jnp.array([[2, 3], [8, 9]])

# Set the number of nearest neighbors to consider
k = 3

# Perform k-NN classification
knn = NearestNeighborsClassifier()
test_y = knn.predict(train_X, train_y, test_X, k)
test_y

(2, 5)
[[1.41421356 1.41421356 4.24264069 7.07106781 9.89949494]
 [9.89949494 7.07106781 4.24264069 1.41421356 1.41421356]]
[[0 1 2]
 [3 4 2]]
(5, 2) (5,) (2, 2) 3 (2, 3)


Array([0, 0], dtype=int32)

In [3]:
import jax.numpy as jnp

# Define an input array
ar = jnp.array([3, 2, 1, 3, 2, 4, 4])

# Get the unique elements of the array
unique_elements = jnp.unique(ar)

# Get the unique elements along with their counts
unique_elements, counts = jnp.unique(ar, return_counts=True)

print("Unique elements:", unique_elements)
print("Counts:", counts)


Unique elements: [1 2 3 4]
Counts: [1 2 2 2]
